---
- name: Running FastQ-to-VCF pipeline
  hosts: localhost
  vars_prompt:
  - name: dir
    prompt: "Enter your full group directory path"
    private: no
  - name: storage_answer
    prompt: "Do you require read/write to any Zeus storage other than your scratch directory? If yes, please enter all separated by space. (Enter for no)"
    private: no
  - name: storage_confirmation
    prompt: "Please confirm that any additional Zeus storage directories are as above (Enter y or n)"
    private: no
  - name: scripts_dir
    prompt: "Enter the name of your scripts directory (relative or absolute)"
    private: no
  - name: cohort_name
    prompt: "Enter your cohort name / the basename of your config file"
    private: no
  - name: ref_dir
    prompt: "Enter the full path to your reference directory"
    private: no
  - name: ref
    prompt: "Enter the name of your reference genome sequence (include suffix)"
    private: no
  tasks:    
  - name: Starting a Slurm interactive session
    command: salloc -n 1 -t 1:00:00 --account=$PAWSEY_PROJECT
  - name: Create directory
    ansible.builtin.file:
      path: "{{ dir }}/{{ ansible_project_name }}"
      state: directory
  - name: Downloading scripts
    shell: 
      cmd: git clone {{ dl_scripts_1 }} && git clone {{ dl_scripts_2 }}
      chdir: "{{ ansible_project_name }}"
      creates: "{{ scripts_1_dir }}"
    register: scriptdir
    tags: scriptdir
  # - debug: 
  #     msg: "{{ scriptdir.stdout }}"
  - name: Changing variables for Pawsey systems
    shell: |
      cd {{ dir }}/{{ ansible_project_name }}/{{ scripts_1_dir }}
      sed -i "s|Gadi|Zeus|g" {{ create_project_script }}
      sed -i "s|{project}|PAWSEY_PROJECT|g" {{ create_project_script }}
      sed -i "s|PBS|slurm|g" {{ create_project_script }}
      sed -i "s|NCI|Pawsey|g" {{ create_project_script }}
      sed -i "s|pbs|script|g" {{ create_project_script }}
  - name: Creating project
    expect:
     chdir: "{{ ansible_project_name }}"
     command: bash {{ scripts_1_dir }}/{{ create_project_script }}
     echo: yes
     responses:
        If yes, please enter all separated by space \[enter for no\]: "{{ storage_answer }}"
        Is this correct? Enter y or n: "{{ storage_confirmation }}"
        Enter the name of your scripts directory \(relative or absolute\): "{{ scripts_dir }}"
        Enter your cohort name / the basename of your config file: "{{ cohort_name }}"
        Enter the name of your Pawsey project: "$PAWSEY_PROJECT"
        Enter the full path to your reference directory: "{{ ref_dir }}"
        Enter the name of your reference genome sequence \(include suffix\): "{{ ref }}"